name: Build TalentEditor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'build'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: '>=1.20'

      - name: Install C Cross-Compiler (for Windows target)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Install dependencies
        run: |
          go mod tidy -C src

      - name: Make build dir
        run: |
          mkdir -p bin

      # Windows
      - name: Build Windows binary
        run: |
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -C src -ldflags="-H=windowsgui" -o ../bin/TalentEditor.exe
      - uses: actions/upload-artifact@v4
        with:
          name: TalentEditor
          path: bin/TalentEditor.exe